[project]
name = "ask"
version = "0.1.0"
description = "A simple CLI tool to ask LLMs a question."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "rich>=13.9.4",
]
